2023-03-30 16:58:16,823:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 16:58:16,824:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 16:58:16,824:INFO:discord.client: logging in using static token
2023-03-30 16:58:18,578:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 62c514d63a5735ae6e99b9b45828ddcc).
2023-03-30 16:58:33,821:INFO:root: <@1090119054754316298> hi
2023-03-30 16:58:33,824:INFO:root: <@1090119054754316298> hi
2023-03-30 16:58:41,828:INFO:root: <@1090119054754316298> add
2023-03-30 16:58:41,828:INFO:root: <@1090119054754316298> add
2023-03-30 16:59:54,816:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 16:59:54,816:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 16:59:54,817:INFO:discord.client: logging in using static token
2023-03-30 16:59:56,405:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: db9964ff179a230f8a913be0ea8eb734).
2023-03-30 17:00:02,268:INFO:root: <@1090119054754316298> add
2023-03-30 17:00:02,270:INFO:root: ['<@1090119054754316298>', 'add']
2023-03-30 17:15:47,137:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 17:15:47,139:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 17:15:47,139:INFO:discord.client: logging in using static token
2023-03-30 17:15:48,935:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: dffecaa32f752ace356df94eaff392e3).
2023-03-30 17:16:26,298:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 17:16:26,300:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:16:26,300:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 17:16:26,338:INFO:root: Connected.
2023-03-30 17:16:26,338:INFO:root: Reading data...
2023-03-30 17:16:26,343:ERROR:discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/discord_bot.py", line 95, in on_message
    await add_tasks(taskname, deadline, is_important, is_urgent)
TypeError: object NoneType can't be used in 'await' expression
2023-03-30 17:16:58,099:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 17:16:58,100:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 17:16:58,101:INFO:discord.client: logging in using static token
2023-03-30 17:16:59,778:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: fcbffc90b779a996d457965092f71356).
2023-03-30 17:17:05,324:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 17:17:05,324:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:17:05,325:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 17:17:05,358:INFO:root: Connected.
2023-03-30 17:17:05,358:INFO:root: Reading data...
2023-03-30 17:21:25,832:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 17:21:25,834:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:21:25,834:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 17:21:25,896:INFO:root: Connected.
2023-03-30 17:21:25,897:INFO:root: Reading data...
2023-03-30 17:21:25,897:ERROR:discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/discord_bot.py", line 95, in on_message
    add_tasks(taskname, deadline, is_important, is_urgent)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/discord_bot.py", line 72, in add_tasks
    cur.execute("INSERT INTO tasks VALUES (%s, %s, %s, %s)", (taskname, deadline, is_important, is_urgent))
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

2023-03-30 17:22:45,902:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 17:22:45,903:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 17:22:45,904:INFO:discord.client: logging in using static token
2023-03-30 17:22:47,563:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: dd9acb70adf977e6aa45a9aae5c9ab4f).
2023-03-30 17:22:52,198:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 17:22:52,198:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:22:52,198:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 17:22:52,217:INFO:root: Connected.
2023-03-30 17:22:52,217:INFO:root: Reading data...
2023-03-30 17:26:01,223:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 17:26:01,224:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 17:26:01,225:INFO:discord.client: logging in using static token
2023-03-30 17:26:03,016:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: c81f4072ad0e62722a157fd64c1957cd).
2023-03-30 17:26:10,275:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 17:26:10,277:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:26:10,277:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 17:26:10,310:INFO:root: Connected.
2023-03-30 17:26:10,310:INFO:root: Reading data...
2023-03-30 17:27:43,359:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 17:27:43,363:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 17:27:43,377:INFO:discord.client: logging in using static token
2023-03-30 17:27:44,959:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: ddb3ef41845fd43f3598df2003b4367e).
2023-03-30 17:28:08,867:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 17:28:08,868:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:28:08,869:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 17:28:08,912:INFO:root: Connected.
2023-03-30 17:28:08,913:INFO:root: Reading data...
2023-03-30 17:28:08,913:ERROR:discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/discord_bot.py", line 97, in on_message
    add_tasks(taskname, deadline, is_important, is_urgent)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/discord_bot.py", line 72, in add_tasks
    cur.execute("INSERT INTO tasks VALUES (%s, %s, %s, %s)", (taskname, deadline, is_important, is_urgent))
psycopg2.InterfaceError: cursor already closed
2023-03-30 17:29:08,160:INFO:discord.gateway: Shard ID None has successfully RESUMED session ddb3ef41845fd43f3598df2003b4367e.
2023-03-30 17:29:18,540:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 17:29:18,541:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 17:29:18,546:INFO:discord.client: logging in using static token
2023-03-30 17:29:20,296:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 74a12ad8fbcf7652a52c83a25add0982).
2023-03-30 17:29:38,336:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 17:29:38,338:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:29:38,338:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 17:29:38,387:INFO:root: Connected.
2023-03-30 17:29:38,388:INFO:root: Reading data...
2023-03-30 17:36:55,460:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 17:36:55,461:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 17:36:55,461:INFO:discord.client: logging in using static token
2023-03-30 17:36:57,240:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: a37c85832ecab3d4a0a4f533c1c7f3de).
2023-03-30 17:37:28,355:INFO:root: <@1090119054754316298> delete do_homework 11/2/2024 important not_urgent
2023-03-30 17:37:28,356:INFO:root: ['<@1090119054754316298>', 'delete', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:38:07,677:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 17:38:07,679:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:38:07,679:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 17:38:07,736:INFO:root: Connected.
2023-03-30 17:38:07,736:INFO:root: Reading data...
2023-03-30 17:40:04,026:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 17:40:04,039:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 17:40:04,049:INFO:discord.client: logging in using static token
2023-03-30 17:40:05,805:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: b96506f33684ac93f8f4e87de918ab44).
2023-03-30 17:40:43,989:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 17:40:43,991:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:40:43,991:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 17:40:44,035:INFO:root: Connected.
2023-03-30 17:40:44,035:INFO:root: Reading data...
2023-03-30 17:42:32,342:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 17:42:32,343:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 17:42:32,343:INFO:discord.client: logging in using static token
2023-03-30 17:42:34,061:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 6f726f005e041ec06c9c067e0446e888).
2023-03-30 17:42:42,567:INFO:root: <@1090119054754316298> delete do_homework
2023-03-30 17:42:42,568:INFO:root: ['<@1090119054754316298>', 'delete', 'do_homework']
2023-03-30 17:43:17,821:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 17:43:17,822:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 17:43:17,822:INFO:discord.client: logging in using static token
2023-03-30 17:43:19,506:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 01e35a93755286f86064b3b091759704).
2023-03-30 17:43:53,523:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 17:43:53,526:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:43:53,526:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 17:43:53,577:INFO:root: Connected.
2023-03-30 17:43:53,577:INFO:root: Reading data...
2023-03-30 17:44:06,874:INFO:root: <@1090119054754316298> add do_assignment 11/2/2024 important not_urgent
2023-03-30 17:44:06,875:INFO:root: ['<@1090119054754316298>', 'add', 'do_assignment', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:44:06,876:INFO:root: taskname: do_assignment, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 17:44:06,897:INFO:root: Connected.
2023-03-30 17:44:06,897:INFO:root: Reading data...
2023-03-30 17:44:32,865:INFO:root: <@1090119054754316298> delete do_homework
2023-03-30 17:44:32,867:INFO:root: ['<@1090119054754316298>', 'delete', 'do_homework']
2023-03-30 17:46:19,544:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 17:46:19,545:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 17:46:19,545:INFO:discord.client: logging in using static token
2023-03-30 17:46:21,269:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 0eb9ae82c12b4d434d409f05ab55acc0).
2023-03-30 17:46:28,206:INFO:root: <@1090119054754316298> delete do_homework
2023-03-30 17:46:28,208:INFO:root: ['<@1090119054754316298>', 'delete', 'do_homework']
2023-03-30 17:46:28,208:ERROR:discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/discord_bot.py", line 113, in on_message
    taskname = result[3]
IndexError: list index out of range
2023-03-30 17:46:58,163:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 17:46:58,164:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 17:46:58,165:INFO:discord.client: logging in using static token
2023-03-30 17:46:59,769:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: c6789d6ac75b72f1ded25d3845efd34d).
2023-03-30 17:47:18,587:INFO:root: <@1090119054754316298> add do_assignment 11/2/2024 important not_urgent
2023-03-30 17:47:18,589:INFO:root: ['<@1090119054754316298>', 'add', 'do_assignment', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:47:18,590:INFO:root: taskname: do_assignment, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 17:47:18,654:INFO:root: Connected.
2023-03-30 17:47:18,654:INFO:root: Reading data...
2023-03-30 17:47:26,473:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 17:47:26,474:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 17:47:26,474:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 17:47:26,495:INFO:root: Connected.
2023-03-30 17:47:26,495:INFO:root: Reading data...
2023-03-30 17:47:38,846:INFO:root: <@1090119054754316298> delete do_homework
2023-03-30 17:47:38,847:INFO:root: ['<@1090119054754316298>', 'delete', 'do_homework']
2023-03-30 17:47:38,847:INFO:root: taskname: do_homework
2023-03-30 17:47:38,884:INFO:root: Connected.
2023-03-30 17:47:38,884:INFO:root: Reading data...
2023-03-30 19:16:55,442:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:16:55,444:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:16:55,444:INFO:discord.client: logging in using static token
2023-03-30 19:16:57,273:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 27e5f7d0f64d09d36548d5de172ed806).
2023-03-30 19:17:05,531:INFO:root: <@1090119054754316298> list
2023-03-30 19:17:05,532:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:17:05,532:INFO:root: list all task
2023-03-30 19:17:05,569:INFO:root: Connected.
2023-03-30 19:17:05,570:INFO:root: Reading data...
2023-03-30 19:18:10,691:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:18:10,692:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:18:10,693:INFO:discord.client: logging in using static token
2023-03-30 19:18:12,495:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: c77cc2549d0912eb7f662808f4734923).
2023-03-30 19:18:17,512:INFO:root: <@1090119054754316298> list
2023-03-30 19:18:17,513:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:18:17,513:INFO:root: list all task
2023-03-30 19:18:17,537:INFO:root: Connected.
2023-03-30 19:18:17,537:INFO:root: Reading data...
2023-03-30 19:18:17,546:INFO:root: Finished.
2023-03-30 19:20:06,190:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:20:06,192:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:20:06,192:INFO:discord.client: logging in using static token
2023-03-30 19:20:07,800:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: eb8cf3b8bd56d385921618d5281bbe0d).
2023-03-30 19:20:12,949:INFO:root: <@1090119054754316298> list
2023-03-30 19:20:12,951:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:20:12,951:INFO:root: list all task
2023-03-30 19:20:12,985:INFO:root: Connected.
2023-03-30 19:20:12,986:INFO:root: Reading data...
2023-03-30 19:20:12,991:INFO:root: Finished.
2023-03-30 19:20:13,392:ERROR:discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/discord_bot.py", line 137, in on_message
    await message.channel.send(sentence)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
2023-03-30 19:21:18,197:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:21:18,199:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:21:18,200:INFO:discord.client: logging in using static token
2023-03-30 19:21:19,709:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: a0d50cb2e2510797f5f358b6b239694b).
2023-03-30 19:21:26,116:INFO:root: <@1090119054754316298> list
2023-03-30 19:21:26,117:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:21:26,118:INFO:root: list all task
2023-03-30 19:21:26,159:INFO:root: Connected.
2023-03-30 19:21:26,159:INFO:root: Reading data...
2023-03-30 19:21:26,169:INFO:root: Finished.
2023-03-30 19:22:14,931:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:22:14,932:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:22:14,932:INFO:discord.client: logging in using static token
2023-03-30 19:22:16,438:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 8a0b744129d032efd6fd1b2991698403).
2023-03-30 19:22:27,646:INFO:root: <@1090119054754316298> list
2023-03-30 19:22:27,648:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:22:27,648:INFO:root: list all task
2023-03-30 19:22:27,679:INFO:root: Connected.
2023-03-30 19:22:27,679:INFO:root: Reading data...
2023-03-30 19:22:27,686:INFO:root: Finished.
2023-03-30 19:22:27,686:ERROR:discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/discord_bot.py", line 137, in on_message
    await message.channel.send(f'1.{all_tasks[0][0]}\n2.\n3.\n')
IndexError: list index out of range
2023-03-30 19:23:17,981:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:23:17,984:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:23:17,991:INFO:discord.client: logging in using static token
2023-03-30 19:23:19,472:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 2424a5f138ae5163cfdeda2986d1ca96).
2023-03-30 19:23:25,503:INFO:root: <@1090119054754316298> list
2023-03-30 19:23:25,504:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:23:25,504:INFO:root: list all task
2023-03-30 19:23:25,543:INFO:root: Connected.
2023-03-30 19:23:25,543:INFO:root: Reading data...
2023-03-30 19:23:25,549:INFO:root: Finished.
2023-03-30 19:24:43,036:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:24:43,037:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:24:43,037:INFO:discord.client: logging in using static token
2023-03-30 19:24:44,677:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: e122022cfa19b65fe8156a54b30dece5).
2023-03-30 19:24:50,185:INFO:root: <@1090119054754316298> list
2023-03-30 19:24:50,187:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:24:50,187:INFO:root: list all task
2023-03-30 19:24:50,220:INFO:root: Connected.
2023-03-30 19:24:50,220:INFO:root: Reading data...
2023-03-30 19:24:50,227:INFO:root: Finished.
2023-03-30 19:24:50,595:ERROR:discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/discord_bot.py", line 138, in on_message
    await message.channel.send(f'{sentence}')
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
2023-03-30 19:26:40,550:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:26:40,551:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:26:40,551:INFO:discord.client: logging in using static token
2023-03-30 19:26:42,212:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 15c00c2705129cfb1f3b1760217df910).
2023-03-30 19:26:47,036:INFO:root: <@1090119054754316298> list
2023-03-30 19:26:47,037:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:26:47,037:INFO:root: list all task
2023-03-30 19:26:47,089:INFO:root: Connected.
2023-03-30 19:26:47,090:INFO:root: Reading data...
2023-03-30 19:26:47,104:INFO:root: Finished.
2023-03-30 19:27:23,669:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:27:23,670:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:27:23,670:INFO:discord.client: logging in using static token
2023-03-30 19:27:25,271:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 2671a1b53d892426a2cd6575a3afc11c).
2023-03-30 19:27:29,669:INFO:root: <@1090119054754316298> list
2023-03-30 19:27:29,670:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:27:29,670:INFO:root: list all task
2023-03-30 19:27:29,704:INFO:root: Connected.
2023-03-30 19:27:29,705:INFO:root: Reading data...
2023-03-30 19:27:29,710:INFO:root: Finished.
2023-03-30 19:28:12,809:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:28:12,824:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:28:12,829:INFO:discord.client: logging in using static token
2023-03-30 19:28:14,593:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: fe6302b27449531bee1af751d967375c).
2023-03-30 19:28:18,208:INFO:root: <@1090119054754316298> list
2023-03-30 19:28:18,209:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:28:18,209:INFO:root: list all task
2023-03-30 19:28:18,255:INFO:root: Connected.
2023-03-30 19:28:18,255:INFO:root: Reading data...
2023-03-30 19:28:18,263:INFO:root: Finished.
2023-03-30 19:28:18,264:INFO:root: []
2023-03-30 19:30:05,762:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:30:05,769:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:30:05,772:INFO:discord.client: logging in using static token
2023-03-30 19:30:07,348:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: dbab46bff8c41e226863030debe615c3).
2023-03-30 19:30:11,809:INFO:root: <@1090119054754316298> list
2023-03-30 19:30:11,810:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:30:11,810:INFO:root: list all task
2023-03-30 19:30:11,836:INFO:root: Connected.
2023-03-30 19:30:11,837:INFO:root: Reading data...
2023-03-30 19:30:11,843:INFO:root: Finished.
2023-03-30 19:30:11,844:INFO:root: []
2023-03-30 19:31:01,293:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:31:01,294:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:31:01,294:INFO:discord.client: logging in using static token
2023-03-30 19:31:02,893:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: b1be67942ae2742941e4907393bbc0ea).
2023-03-30 19:31:06,344:INFO:root: <@1090119054754316298> list
2023-03-30 19:31:06,344:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:31:06,344:INFO:root: list all task
2023-03-30 19:31:06,388:INFO:root: Connected.
2023-03-30 19:31:06,388:INFO:root: Reading data...
2023-03-30 19:31:06,397:INFO:root: []
2023-03-30 19:31:06,402:INFO:root: Finished.
2023-03-30 19:31:06,402:INFO:root: []
2023-03-30 19:37:36,052:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:37:36,054:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:37:36,063:INFO:discord.client: logging in using static token
2023-03-30 19:37:37,791:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 9ab0e80dc90dfba614948654b10e61ab).
2023-03-30 19:37:51,132:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 19:37:51,133:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 19:37:51,133:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 19:37:51,193:INFO:root: Connected.
2023-03-30 19:37:51,193:INFO:root: Reading data...
2023-03-30 19:38:09,727:INFO:root: <@1090119054754316298> add do_assignment 11/2/2024 important not_urgent
2023-03-30 19:38:09,729:INFO:root: ['<@1090119054754316298>', 'add', 'do_assignment', '11/2/2024', 'important', 'not_urgent']
2023-03-30 19:38:09,729:INFO:root: taskname: do_assignment, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 19:38:09,784:INFO:root: Connected.
2023-03-30 19:38:09,785:INFO:root: Reading data...
2023-03-30 19:38:17,769:INFO:root: <@1090119054754316298> list
2023-03-30 19:38:17,770:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:38:17,770:INFO:root: list all task
2023-03-30 19:38:17,793:INFO:root: Connected.
2023-03-30 19:38:17,794:INFO:root: Reading data...
2023-03-30 19:38:17,798:INFO:root: [('do_homework', '11/2/2024', 'important', 'not_urgent'), ('do_assignment', '11/2/2024', 'important', 'not_urgent')]
2023-03-30 19:38:17,799:INFO:root: Finished.
2023-03-30 19:38:17,799:INFO:root: [('do_homework', '11/2/2024', 'important', 'not_urgent'), ('do_assignment', '11/2/2024', 'important', 'not_urgent')]
2023-03-30 19:38:17,799:INFO:root: 1. task_name:do_homework, deadline:11/2/2024, important not_urgent

2023-03-30 19:38:17,800:INFO:root: 2. task_name:do_assignment, deadline:11/2/2024, important not_urgent

2023-03-30 19:38:43,111:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:38:43,112:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:38:43,120:INFO:discord.client: logging in using static token
2023-03-30 19:38:44,949:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 7fecca41cd660cf3d284ba34fd2b172c).
2023-03-30 19:38:50,916:INFO:root: <@1090119054754316298> list
2023-03-30 19:38:50,917:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:38:50,917:INFO:root: list all task
2023-03-30 19:38:50,937:INFO:root: Connected.
2023-03-30 19:38:50,937:INFO:root: Reading data...
2023-03-30 19:38:50,944:INFO:root: []
2023-03-30 19:38:50,945:INFO:root: Finished.
2023-03-30 19:38:50,945:INFO:root: []
2023-03-30 19:38:51,329:ERROR:discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/discord_bot.py", line 143, in on_message
    await message.channel.send(f'{sentence}')
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
2023-03-30 19:39:51,023:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:39:51,024:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:39:51,025:INFO:discord.client: logging in using static token
2023-03-30 19:39:52,858:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: bd8cf9fa08877ccfbf6a66afc2df6259).
2023-03-30 19:40:06,726:INFO:root: <@1090119054754316298> add do_assignment 11/2/2024 important not_urgent
2023-03-30 19:40:06,728:INFO:root: ['<@1090119054754316298>', 'add', 'do_assignment', '11/2/2024', 'important', 'not_urgent']
2023-03-30 19:40:06,728:INFO:root: taskname: do_assignment, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 19:40:06,778:INFO:root: Connected.
2023-03-30 19:40:06,778:INFO:root: Reading data...
2023-03-30 19:40:19,610:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 19:40:19,611:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 19:40:19,612:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 19:40:19,629:INFO:root: Connected.
2023-03-30 19:40:19,629:INFO:root: Reading data...
2023-03-30 19:40:45,845:INFO:root: <@1090119054754316298> list
2023-03-30 19:40:45,846:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:40:45,846:INFO:root: list all task
2023-03-30 19:40:45,898:INFO:root: Connected.
2023-03-30 19:40:45,898:INFO:root: Reading data...
2023-03-30 19:40:45,907:INFO:root: [('do_assignment', '11/2/2024', 'important', 'not_urgent'), ('do_homework', '11/2/2024', 'important', 'not_urgent')]
2023-03-30 19:40:45,908:INFO:root: Finished.
2023-03-30 19:40:45,908:INFO:root: [('do_assignment', '11/2/2024', 'important', 'not_urgent'), ('do_homework', '11/2/2024', 'important', 'not_urgent')]
2023-03-30 19:40:45,908:INFO:root: 1. task_name:do_assignment, deadline:11/2/2024, important not_urgent

2023-03-30 19:40:45,909:INFO:root: 2. task_name:do_homework, deadline:11/2/2024, important not_urgent

2023-03-30 19:41:18,507:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:41:18,511:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:41:18,512:INFO:discord.client: logging in using static token
2023-03-30 19:41:20,290:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 4f969f0e4a3165d4d247b235fbab0fe9).
2023-03-30 19:41:24,207:INFO:root: <@1090119054754316298> list
2023-03-30 19:41:24,208:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:41:24,208:INFO:root: list all task
2023-03-30 19:41:24,251:INFO:root: Connected.
2023-03-30 19:41:24,251:INFO:root: Reading data...
2023-03-30 19:41:24,255:INFO:root: []
2023-03-30 19:41:24,256:INFO:root: Finished.
2023-03-30 19:41:24,256:INFO:root: []
2023-03-30 19:45:03,928:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:45:03,930:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:45:03,930:INFO:discord.client: logging in using static token
2023-03-30 19:45:05,702:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: b3511b831d841e7934f80fdd34c9eb12).
2023-03-30 19:45:13,804:INFO:root: <@1090119054754316298> add do_homework 11/2/2024 important not_urgent
2023-03-30 19:45:13,805:INFO:root: ['<@1090119054754316298>', 'add', 'do_homework', '11/2/2024', 'important', 'not_urgent']
2023-03-30 19:45:13,805:INFO:root: taskname: do_homework, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 19:45:13,934:INFO:root: Connected.
2023-03-30 19:45:13,935:INFO:root: Reading data...
2023-03-30 19:45:21,466:INFO:root: <@1090119054754316298> add do_assignment 11/2/2024 important not_urgent
2023-03-30 19:45:21,466:INFO:root: ['<@1090119054754316298>', 'add', 'do_assignment', '11/2/2024', 'important', 'not_urgent']
2023-03-30 19:45:21,467:INFO:root: taskname: do_assignment, deadline: 11/2/2024, is_important: important, is_Urgent: not_urgent
2023-03-30 19:45:21,485:INFO:root: Connected.
2023-03-30 19:45:21,485:INFO:root: Reading data...
2023-03-30 19:45:44,444:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2023-03-30 19:45:44,453:DEBUG:asyncio: Using selector: KqueueSelector
2023-03-30 19:45:44,458:INFO:discord.client: logging in using static token
2023-03-30 19:45:46,289:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: cf5990f457b96ac79f05d0b3ec9b9894).
2023-03-30 19:45:59,051:INFO:root: <@1090119054754316298> list
2023-03-30 19:45:59,053:INFO:root: ['<@1090119054754316298>', 'list']
2023-03-30 19:45:59,053:INFO:root: list all task
2023-03-30 19:45:59,106:INFO:root: Connected.
2023-03-30 19:45:59,106:INFO:root: Reading data...
2023-03-30 19:45:59,112:INFO:root: [('do_homework', '11/2/2024', 'important', 'not_urgent'), ('do_assignment', '11/2/2024', 'important', 'not_urgent')]
2023-03-30 19:45:59,113:INFO:root: Finished.
2023-03-30 19:45:59,113:INFO:root: [('do_homework', '11/2/2024', 'important', 'not_urgent'), ('do_assignment', '11/2/2024', 'important', 'not_urgent')]
2023-03-30 19:45:59,113:INFO:root: 1. task_name:do_homework, deadline:11/2/2024, important not_urgent

2023-03-30 19:45:59,113:INFO:root: 2. task_name:do_assignment, deadline:11/2/2024, important not_urgent

2023-03-30 20:13:33,328:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-30 20:13:39,405:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 0a2996a9e367ce4f733b64a505f166e4).
2023-03-30 20:33:44,508:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-30 20:33:50,680:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 1314e3d37275a747805d7204e7089ef6).
2023-03-30 20:53:40,106:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-30 20:53:46,438:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: cf3ff9f6679682b2345220e044c48bce).
2023-03-30 21:11:49,004:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-30 21:11:55,256:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 0218e3a3ced0e5d19a369c02b126bd57).
2023-03-30 21:14:07,570:ERROR:discord.client: Attempting a reconnect in 0.57s
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
2023-03-30 21:14:08,888:INFO:discord.gateway: Shard ID None has successfully RESUMED session 0218e3a3ced0e5d19a369c02b126bd57.
2023-03-30 21:16:19,511:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-30 21:16:25,799:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 8bd6235b8e72f312d573603ffbca78ef).
2023-03-30 21:21:59,837:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-30 21:22:05,894:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 5c4fe539c2b76b8f6ff3e7afda30007d).
2023-03-30 21:25:44,632:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-30 21:25:50,656:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 92f7c8a623f58d523c29c6ec06840667).
2023-03-30 21:40:24,184:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-30 21:40:30,250:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 8da80a0fd1a8c86f08597391a99ef347).
2023-03-30 21:46:04,836:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-30 21:46:10,977:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: b9fdfd7ef49b1aa379f9fbfcc78ec5ce).
2023-03-30 21:51:45,048:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-30 21:51:51,189:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: d35463f3d06f4826b68fd39b9940b360).
2023-03-30 23:08:38,562:INFO:discord.gateway: Shard ID None has successfully RESUMED session d35463f3d06f4826b68fd39b9940b360.
2023-03-30 23:50:06,672:INFO:root: <@1090119054754316298> add cleaning_room NAN not_important not_urgent
2023-03-30 23:50:06,673:INFO:root: ['<@1090119054754316298>', 'add', 'cleaning_room', 'NAN', 'not_important', 'not_urgent']
2023-03-30 23:50:06,674:INFO:root: taskname: cleaning_room, deadline: NAN, is_important: not_important, is_Urgent: not_urgent
2023-03-30 23:50:06,728:INFO:root: Connected.
2023-03-30 23:50:06,729:INFO:root: Reading data...
2023-03-30 23:58:58,656:INFO:discord.gateway: Shard ID None has successfully RESUMED session d35463f3d06f4826b68fd39b9940b360.
2023-03-31 01:18:16,192:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-31 01:18:22,338:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 2f8358234e32fac441b8978da116edde).
2023-03-31 01:23:57,559:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-31 01:24:03,606:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 7040ac49c07bbe2ed5a374a79cb38f92).
2023-03-31 01:29:38,893:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-31 01:29:44,944:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 7549aa6109b4b1ba0b1c686bd905e8ac).
2023-03-31 02:23:21,355:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-31 02:35:39,472:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-31 02:35:58,494:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 88194df5964f8fa1e109d37309e39395).
2023-03-31 02:37:45,881:INFO:discord.gateway: Shard ID None has successfully RESUMED session 88194df5964f8fa1e109d37309e39395.
2023-03-31 02:38:45,684:ERROR:discord.client: Attempting a reconnect in 1.18s
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
2023-03-31 02:38:47,615:INFO:discord.gateway: Shard ID None has successfully RESUMED session 88194df5964f8fa1e109d37309e39395.
2023-03-31 02:39:46,092:ERROR:discord.client: Attempting a reconnect in 3.71s
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
2023-03-31 02:39:50,462:INFO:discord.gateway: Shard ID None has successfully RESUMED session 88194df5964f8fa1e109d37309e39395.
2023-03-31 03:33:32,266:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-31 03:50:41,550:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-31 06:02:04,880:ERROR:discord.client: Attempting a reconnect in 0.08s
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-03-31 06:02:05,653:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-31 06:32:59,723:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-31 06:50:54,849:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-31 07:24:12,965:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-31 07:40:50,661:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-31 08:04:11,661:ERROR:discord.client: Attempting a reconnect in 11.28s
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1055, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1040, in create_connection
    sock = await self._connect_sock(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 954, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
OSError: [Errno 51] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway.discord.gg:443 ssl:default [Network is unreachable]
2023-03-31 08:04:22,998:ERROR:discord.client: Attempting a reconnect in 3.89s
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 855, in getaddrinfo
    return await self.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway.discord.gg:443 ssl:default [nodename nor servname provided, or not known]
2023-03-31 08:19:52,641:ERROR:discord.client: Attempting a reconnect in 5.82s
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 855, in getaddrinfo
    return await self.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway.discord.gg:443 ssl:default [nodename nor servname provided, or not known]
2023-03-31 08:36:38,125:ERROR:discord.client: Attempting a reconnect in 123.54s
Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 855, in getaddrinfo
    return await self.run_in_executor(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/sutthikant.k/Documents/Habour.Space/NewModule10/Final Project/finalEnv/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway.discord.gg:443 ssl:default [nodename nor servname provided, or not known]
2023-03-31 09:14:34,617:INFO:discord.gateway: Shard ID None session has been invalidated.
2023-03-31 09:14:40,569:INFO:discord.gateway: Shard ID None has connected to Gateway (Session ID: 09446eaa7fd8e22e165acc7a6887b04c).
